### ISSUE TITLE
[FEATURE]- Developing an relaxation Page/ Section?

### ISSUE THREAD

**Issue by elsamird003** [rthurston1/Team01-Web-Application-Cherish#106]
**Describe the feature**

- Relaxation page.
- Daily motivational quote

- This feature allows users that after they had a rough day and felt down, maybe taking some time off doing a little meditation would allow them to get back on track. The idea is to have a dedicated page just for relaxation.
-
**Implementation**
-I'm planning to use HTML.CSS and JS for this feature. I'll create a separate folder called ('Relaxation-page') within the front-end folder. Two more folders will be made, one will be front end and the other one will be called back end. 
- For the motivation quote I'm looking foward on creating it's dedicated div group and css sections. Also I need to implement and API funtionality to make this possoble. 

**Size of Feature**
On the feature point system (1-5pts), determine how big this new feature will be. (1 being a small feature, 5 being a large feature).
The size of this feature is 4-pts,
**Additional Details**
No additional details

**Comment by NikoZBK** [comment]
If we're going to add meditation tips to the app, then I think we'll need a page dedicated to it. Unfortunately designing this page wouldn't count towards milestone 4 grading so I would get a placeholder working asap!

**Comment by rthurston1** [comment]
This is a cool feature, but it's more front-end. Maybe you could use an API to generate possible meditation techniques.
