### ISSUE TITLE
[FEATURE] Notifications 

### ISSUE THREAD

**Issue by WaDaDon-Create** [rthurston1/Team01-Web-Application-Cherish#109]
### Describe the Feature

The **Notifications Backend** will allow the app to send reminders and alerts, improving user engagement. Notifications will include:

- **Daily Check-In Reminders**
- **Weekly Summary Alerts**
- **Personalized Messages** based on user activity.

### Implementation

- **Database**: Add tables for notification preferences and logs.
- **APIs**: Schedule notifications and send alerts (email/app).
- **Frontend Integration**: Allow users to customize notification settings.

This feature will enhance interaction and consistency in mental health tracking.

### Size of Feature

**Medium (4 pts)**

**Comment by rthurston1** [comment]
I've broken down this feature into a potential checklist.

# Notifications Backend Feature Checklist

## 1. Setup and Preparation
- [ ] Install required libraries:
  - `node-cron` for scheduling tasks: `npm install node-cron`
  - `nodemailer` for email notifications: `npm install nodemailer`
  - Optional: Add push notification libraries (e.g., `web-push` or `firebase-admin`) if implementing app notifications.
- [ ] Plan and define the data structures for notification preferences and logs.

---

## 2. Database Updates
- [ ] Add a `NotificationPreferences` table:
  - [ ] Fields:
    - `user_id` (Primary Key, references `User` table)
    - `daily_check_in` (Boolean, default `true`)
    - `weekly_summary` (Boolean, default `true`)
    - `custom_messages` (Boolean, default `true`)
  - [ ] Set up relationships with the `User` table.
- [ ] Add a `NotificationLogs` table:
  - [ ] Fields:
    - `notification_id` (Primary Key)
    - `user_id` (Foreign Key, references `User` table)
    - `type` (Enum: "daily", "weekly", "custom")
    - `status` (Enum: "sent", "failed")
    - `timestamp` (Date/Time)

---

## 3. Backend Logic
### 3.1 Scheduling Notifications
- [ ] Implement a scheduler using `node-cron`:
  - [ ] Schedule daily notifications at a fixed time.
  - [ ] Schedule weekly notifications on a specific day and time.
  - [ ] Include logic to skip notifications if the user has opted out.

### 3.2 Sending Notifications
- [ ] Set up a notification sending service:
  - [ ] Integrate `nodemailer` for email notifications.
  - [ ] Define reusable templates for:
    - Daily Check-In Reminders.
    - Weekly Summary Alerts.
    - Personalized Messages.
- [ ] Log notification delivery status in the `NotificationLogs` table.

### 3.3 Custom Notifications
- [ ] Implement a function to send personalized messages based on user activity.
- [ ] Trigger this function based on specific events (e.g., lack of activity for a week).

---

## 4. Frontend Integration
- [ ] Create a "Notification Settings" page:
  - [ ] Allow users to toggle options for:
    - Daily Check-In Reminders.
    - Weekly Summary Alerts.
    - Personalized Messages.
  - [ ] Save user preferences to the `NotificationPreferences` table via API.
- [ ] Display a history of sent notifications (e.g., "Last Notification Sent: 2 days ago").

---

## 5. API Development
- [ ] Create an API endpoint to update notification preferences:
  - [ ] Input: `user_id`, updated preferences.
  - [ ] Output: Success or error message.
- [ ] Create an API endpoint to retrieve user notification logs:
  - [ ] Input: `user_id`.
  - [ ] Output: List of notifications with type, status, and timestamp.
- [ ] Create an API endpoint to trigger custom notifications (Admin only).

---

## 6. Testing
- [ ] Test database schema changes.
- [ ] Test the scheduler to ensure notifications are sent at the correct times.
- [ ] Test email notifications for:
  - [ ] Daily Check-In Reminders.
  - [ ] Weekly Summary Alerts.
  - [ ] Personalized Messages.
- [ ] Test frontend notification settings page to ensure changes are saved and loaded correctly.
- [ ] Test API endpoints for expected functionality.

---

## Final Checklist
- [ ] Libraries installed.
- [ ] Database updated with `NotificationPreferences` and `NotificationLogs` tables.
- [ ] Scheduler for daily and weekly notifications implemented.
- [ ] Email notification service integrated.
- [ ] Custom notifications triggered by user activity or events.
- [ ] Notification settings page created on the frontend.
- [ ] API endpoints for preferences, logs, and custom notifications developed.
- [ ] Feature tested thoroughly.

**Comment by rthurston1** [comment]
We won't have time to do this.
