### ISSUE TITLE
[#104] [LARGE TASK] Implement the models and the model factory

### ISSUE THREAD

**Issue by NikoZBK** [rthurston1/Team01-Web-Application-Cherish#114]
**Description**: Implement the models in back-end\src\model including the model factory

**Tag**: #104 

**Owner**: @NikoZBK 

**Expected Outcome**: There should be a local and a remote model (sqlite) and we should have a Model Factory that allows us to swap between the two. The models will perform CRUD operations on data. The local model should work on an array whereas the sqlite model will perform CRUD operations on sequelize models. This feature/task will be broken down into smaller tasks and referenced by tag #114. I have most if not all the code written already [here](https://github.com/rthurston1/Team01-Web-Application-Cherish/tree/backend-scaffolding-niko/back-end/src/model) but I would like a fresh set of eyes.

**Comment by rthurston1** [comment]
This has been completed
