### ISSUE TITLE
[#105][SMALL TASK] Register a User

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#118]
**Description**
Create a function within the database model to add a new user entry to the database

**Issue Tag: ** #105

**Expected Outcome**
The inputted username and password should be added to the SQLite Database

**Comment by rthurston1** [comment]
This is already completed, just wanted to make it an official task.

**Comment by rthurston1** [comment]
I need to redo this with the new implementation of the database

[Commit](https://github.com/rthurston1/Team01-Web-Application-Cherish/commit/565cf3289ded7c36f37ba18b288f14535196b1e5)

**Comment by elsamird003** [comment]
Nice robbie, :). Lmk if you need any help on this

**Comment by jss4830** [comment]
Great work on this!

**Comment by rthurston1** [comment]
This task is done, you can find it in this commit.

[Commit](https://github.com/rthurston1/Team01-Web-Application-Cherish/commit/5759db93c39447301a5e97c93fd0c34727502570)
