### ISSUE TITLE
[#106][MEDIUM FEATURE] User Login

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#119]
**Description**
Validates credential and logs the user into their account

**Issue Tag:** #106

**Expected Outcome**
Once provided the correct username and password, the database should return all the calendar data specific to the user.

**Comment by NikoZBK** [comment]
How's this coming along?

**Comment by rthurston1** [comment]
It been coming along. I had to first implement the sqlite database which I've done here.

[565cf3289ded7c36f37ba18b288f14535196b1e5](https://github.com/rthurston1/Team01-Web-Application-Cherish/commit/565cf3289ded7c36f37ba18b288f14535196b1e5)

**Comment by rthurston1** [comment]
This feature is done, however the database doesn't properly store/retrieve emotions into the database. So I won't be merging it into the main branch. Here is my commit.

[Commit](https://github.com/rthurston1/Team01-Web-Application-Cherish/commit/5759db93c39447301a5e97c93fd0c34727502570)
