### ISSUE TITLE
[#107][SMALL FEATURE] User Login Page

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#120]
**Description**
Create a page that allows the user to type in a username and password to register an account or login into an existing one.

**Issue Tag:** #107

**Expected Outcome**
The page allows the user to type in inputs that then generate requests to the database to validate the credentials. On success, the server should send back the user's calendar data.

**Comment by WaDaDon-Create** [comment]
Sounds good! I can implement this

**Comment by rthurston1** [comment]
How you doing on this Wacil? Is the page almost done?

**Comment by anugrahgeorg** [comment]
@WaDaDon-Create  Any status update on this?

**Comment by elsamird003** [comment]
Hi guys, this is a good idea for the project. Lmk if you need help with the implementation.

**Comment by WaDaDon-Create** [comment]
I have it all done but i'm having a hard time making it a separate page and then once the user logs in then it goes to the main page. I don't know how to implement that. You can take a look at my branch "WacilLogInOffMain"

**Comment by rthurston1** [comment]
You'll need to use the EventHub and publish an event to load the Main Page. The initial startup in `main.js` should load the login page and not the Main Page. You will need to add more events in `Events.js` for the login page.

**Comment by rthurston1** [comment]
Also the LoginPage needs to extend the BaseComponent class like all the others

**Comment by WaDaDon-Create** [comment]
I just finished it! everything is working in terms of the login page being loaded first and I styled it as well

**Comment by rthurston1** [comment]
> I just finished it! everything is working in terms of the login page being loaded first and I styled it as well

Thanks! I will close this issue
