### ISSUE TITLE
[#114] [MEDIUM/HARD TASK] Implement the remote model

### ISSUE THREAD

**Issue by NikoZBK** [rthurston1/Team01-Web-Application-Cherish#121]
**Description**: Implement the remote model in back-end\src\model

**Tag**: #114, #104  

**Owner**: TBD

**Expected Outcome**: A model that performs CRUD operations on sequelize models. The SQLite Model should instantiate a sequelize object as well as define a Day, Emotion, and User model with properties that match our data spec. For example, a Day has a date_id, rating, and a journal. An Emotion has a date_id, emotion_id, magnitude, description, and timestamp.  @rthurston1 is working on user authentication so you may want to collab with him for some of this. Most if not all of the code is already written in my branch [here](https://github.com/rthurston1/Team01-Web-Application-Cherish/blob/backend-scaffolding-niko/back-end/src/model/SQLiteDayModel.js).

**Comment by rthurston1** [comment]
User authentication is a lot more trickier than I thought. I think for now we will ignore it until later.

**Comment by rthurston1** [comment]
It has been done!!!! XD
