### ISSUE TITLE
[#104] [MEDIUM TASK] Implement the back end controller

### ISSUE THREAD

**Issue by NikoZBK** [rthurston1/Team01-Web-Application-Cherish#122]
**Description**: Implement the back end controller class that manages the CRUD operations that are performed by the model. Most if not all the code is written in my branch [here](https://github.com/rthurston1/Team01-Web-Application-Cherish/blob/backend-scaffolding-niko/back-end/src/controller/DayController.js).

**Tag**: #104 

**Owner**: @NikoZBK 

**Expected Outcome**: The Controller should import the model factory and then get the current model. The Controller class leverages the model by calling it's CRUD operations based on function. For example, getDay in the Controller class will call the model's read function to retrieve data.

**Comment by rthurston1** [comment]
I've written the `getYear` and `getMonth` methods
