### ISSUE TITLE
[#114] [SMALL TASK] Implement the model factory

### ISSUE THREAD

**Issue by NikoZBK** [rthurston1/Team01-Web-Application-Cherish#123]
**Description**: Implement the model factory in \back-end\src\model

**Tag**: #114, #104 

**Owner**: TBD

**Expected Outcome**: The model factory selects the model to use for our back-end. The implementation is short, and has already been written [here](https://github.com/rthurston1/Team01-Web-Application-Cherish/blob/0cb67ada042d43c960f64bb5f3230a91c1cf9699/back-end/src/model/ModelFactory.js).

**Comment by rthurston1** [comment]
Done. I will create a merge request
