### ISSUE TITLE
[#138][SMALL-MEDIUM SIZE] Implement DayController methods

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#138]
**Description**
There are a lot of functions to be completed in DayController which will simply uses the methods that I've created in the sqlite database. I'm going to work on `registerUser` as that requires some encryption. Other than that, this should be pretty straight forward. Please make that all inputted data is formatted correctly.

**Issue Tag:** #138

**Owner:** TDB

**Expected Outcome**
Should successfully make calls the database and return the desired data.

**Comment by NikoZBK** [comment]
I'll write the other functions.
