### ISSUE TITLE
[FEATURE] Daily motivational quote! 

### ISSUE THREAD

**Issue by elsamird003** [rthurston1/Team01-Web-Application-Cherish#141]
**Describe the feature**
What does this feature do? 
It gives the user a good vibe, by having a motivational quote the moment the user enters the app. 

**Implementation**
How will the feature be integrated into the project? Ex. What new files/folders may need to be created?
Fetchquote function implemented inside the src/front-end/calendar/Calendarcomponets.js. 
also made changes on the stylescalendar.css file. Created two things ** quote-container**- which gives the style and color of the quote component. Also implemented the***quote author* section 

**Size of Feature**
On the feature point system (1-5pts), determine how big this new feature will be. (1 being a small feature, 5 being a large feature).
  4
**Additional Details**
Any other context relevant to the feature.

![image](https://github.com/user-attachments/assets/ac08dec7-f04c-49a8-a796-010df6aba728)

**Comment by rthurston1** [comment]
Is this complete? Have you made a PR to main yet?

**Comment by jss4830** [comment]
This looks great, Sam! I love the visual style of the quotes and how it fits on the page. I think this really brings the page to life and will make the calendar page more fun to use. Good work.

**Comment by elsamird003** [comment]
> Is this complete? Have you made a PR to main yet?

yes it is
