### ISSUE TITLE
[FEATURE] Global Navigation Menu

### ISSUE THREAD

**Issue by NikoZBK** [rthurston1/Team01-Web-Application-Cherish#31]
**Please Describe The Problem To Be Solved**
Page navigation is currently hard coded depending on the page. I propose we have a persistent menu of options that will allow the user to visit any page they wish without having to visit a particular page first.

**(Optional): Suggest A Solution**
Remove the four buttons on the calendar page and place them into their own component class that will be persistent between view/page changes.

**Comment by anugrahgeorg** [comment]
Agreed! Proposed solution sounds very doable
