### ISSUE TITLE
[FEATURE] Daily Rating

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#52]
**Describe the feature**
Automatically generates a number (1 to 10) representing the average emotion score for the day (It takes the average score of the emotions logged during a day)

**Implementation**
Create a new function within DayComponent.js to handle the logic. 

**Size of Feature**
Small Feature (1 point)

**Additional Details**
Feel free to calculate the average however you'd like.
DUE 11/13/2024 11:59 PM

**Comment by jss4830** [comment]
Hey Robbie, please check out my implementation of this on jesse-day-rating-feature branch

**Comment by rthurston1** [comment]
There's no neutral emotion, can you change that to disgusted please?

**Comment by rthurston1** [comment]
Functionality and element in HTML all set. I know Jesse is thinking about adding a neutral emotion... I will leave this issue open until further notice.
