### ISSUE TITLE
[FIX] Add Correct Emotions Images

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#55]
**What to Fix**
The emotions displayed on the Check-In page do not match with the decided emotions (Not your btw fault Wacil)

**How to Fix It**
Find new gifs that properly fit the description of the following emotions:
 - Happy
 - Sad
 - Angry
 - Anxious
 - Disgusted

**Additional Details**
DUE 11/12/2024 11:59 PM

**Comment by WaDaDon-Create** [comment]
Created a branch called Wacil-CheckInEmoji's with new emotion images
