### ISSUE TITLE
[Feature] Calendar View Streak Proposal [Medium Feature: 3 points]

### ISSUE THREAD

**Issue by anugrahgeorg** [rthurston1/Team01-Web-Application-Cherish#94]
Pretty much with any app development / programming; fresh set of eyes always is helpful. The other day my wife brought up the fact of what's the point of having a whole calendar view if I cant log my journals or emotion entries for previous day? Or for the day before yesterday? And how does it show me even if I did login for the days before today?

And so this got me thinking; why do we even have a calendar view in the first place?

So here is are my thoughts:

1- We made the calendar view originally in the first place to color / bold / highlight the days when the user submits an emotion / check in entry. But since then, we developed the app in a slightly different direction where it is now an emotion and  journal track kind of app. Which is totally amazing and that is not an issue. But this brings me to my next point:

2- If we are in the emotion and journal tracking kind of app, we probably have to ask ourselves why do we need the whole month calendar view. In my opinion, it kinda makes no sense to me to see all the month days when the user is going to log their emotions for just the current day. In that case, we have 2 solutions for this:

      - 1st solution: Remove the whole calendar view and make it to current days date view but keep the previous and next day navigation (instead of navigating months, we will be navigating days). So instead of the user seeing the month, they will see just today's date.
      
      - 2nd Solution: We can keep the month view and add on a feature to our app; where when a user submits at least 1 entry for the day, the day's font in the calendar will go bold, highlighted, or colored differently. This way, the user can see which all days they have tracked their stuff. I am more than happy to work on this back end part 

Either solutions we choose, we have to implement the feature where the users can go to previous days and log in an entry.

**Comment by rthurston1** [comment]
I like solution #2. I think this allows more flexibility. The user can go to back to previous day and edit/add/delete emotions. For instance, the user was tired about didn't have time to log their emotion yesterday but they still want to comment on a big event that happened during that day. We will keep the calendar to allow easier navigation.

**Comment by NikoZBK** [comment]
I agree that we need to have a visual indication that the user has made an entry for a day on the calendar as currently there is no way to tell. I personally would like to go with method 2 where we keep the calendar and have a visual indication of days that have been logged. (Bonus feature: Have all the days in your current streak highlighted to show you're on a streak) 

On this topic we may want to disable clicking on days that haven't happened yet. That could be handled in the event handler code for the day div elements.

**Comment by jss4830** [comment]
Oops I missed this issue post, but great points. I also totally forgot that the original idea was to have the days color coded based on your emotions for that day. I also think solution 2 is probably the way to go. Good thinking!

**Comment by rthurston1** [comment]
I don't think we will have time to complete this.
