### ISSUE TITLE
[FEATURE] Save Summary Page Responses

### ISSUE THREAD

**Issue by rthurston1** [rthurston1/Team01-Web-Application-Cherish#95]
**Describe the feature**
If the user likes the response the AI generated on the summary page, the user can save it into the database.

**Implementation**
Not sure yet. Perhaps make a call to the backend database and save the response to a certain table.

**Size of Feature**
Medium Feature (3pts)

**Comment by jss4830** [comment]
I like this idea!

**Comment by rthurston1** [comment]
This idea is being scrapped.
